# Copyright (C) 2025 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0

on:
  push:
    tags:
      - v*

concurrency:
  group: "release-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true
    
jobs:
  quality_artifacts_job:
    name: A job to collect quality artifacts
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        id: create_release
      - name: Show release URL
        run: |
          echo ${{ steps.create_release.outputs.url }}

      # Upload artifacts to release
      - name: Upload README to release
        uses: svenstaro/upload-release-action@v2
        id: upload_readme
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: README.md
          tag: ${{ github.ref }}
      - name: Upload LICENSE to release
        uses: svenstaro/upload-release-action@v2
        id: upload_license
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: LICENSE
          tag: ${{ github.ref }}

      # Do the quality artifact collection thing
      - name: Collect quality artifacts
        uses: ./ # Uses an action in the root directory
        id: quevee
        with:
          release_url: ${{ steps.create_release.outputs.url }}
          purl_namespace: ${{ github.repository_owner }}
          purl_type: github
          artifacts_readme: |
            ${{ steps.upload_readme.outputs.browser_download_url }}|Project README|README documentation including usage, build and contribution instructions|
          artifacts_requirements: |
            ${{ steps.upload_license.outputs.browser_download_url }}|Project License|Project License text|
            https://yet.another.org/example/artifact.bz2|Example Artifact|Another dummy example artifact link|example_tag
      - name: Upload quality manifest to release
        uses: svenstaro/upload-release-action@v2
        id: upload_manifest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.quevee.outputs.manifest_file }}
          tag: ${{ github.ref }}
      - name: Store quality manifest as workflow artifact
        uses: actions/upload-artifact@v4
        id: store_manifest
        with:
          name: quality-artifacts-manifest
          path: ${{ steps.quevee.outputs.manifest_file }}
      - name: Upload extended quality manifest to release
        uses: svenstaro/upload-release-action@v2
        id: upload_manifest_v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.quevee.outputs.manifest_file_v2 }}
          tag: ${{ github.ref }}
      - name: Store extended quality manifest as workflow artifact
        uses: actions/upload-artifact@v4
        id: store_manifest_v2
        with:
          name: quality-artifacts-manifest_v2
          path: ${{ steps.quevee.outputs.manifest_file_v2 }}
